### ISSUE TITLE
seneca-balance-client should be installed when seneca-mesh is

### ISSUE THREAD

**Issue by nherment** [rjrodger/seneca-mesh#16]
getting dependency error when I only install ``seneca`` and ``seneca-mesh`` about ``seneca-balance-client`` missing. Should it not be an explicit dependency in seneca-mesh ?

**Comment by mcdonnelldean** [comment]
It's a peer depency. Because it can be used by other plugins in and of itself making it an explicit dependency will cause issues down the line.
