### ISSUE TITLE
Deployment inside Docker container

### ISSUE THREAD

**Issue by manoj150283** [rjrodger/seneca-mesh#20]
Hi,

Could you please guide me as how to deploy this inside Docker container. I mean in case of Docker deployment do i need to manually assign host, bases, port etc or it can automatically detect ?

Regards,
- Manoj

**Comment by keerthivasan-r** [comment]
@rjrodger Can you please assist with this?

**Comment by rjrodger** [comment]
You need to use host networking: ---net=host

**Comment by keerthivasan-r** [comment]
@rjrodger  Thank you man, I'll try.

**Comment by rjrodger** [comment]
I still need to write up docs, but I have now verified that everything will work on docker swarm as well - see test/docker
