### ISSUE TITLE
Message: seneca: gate-executor: [TIMEOUT] with dockers

### ISSUE THREAD

**Issue by BhaskaranR** [rjrodger/seneca-mesh#32]
it used to work before on dockers. bringing up a service gives me gate-executor exception. i've the mesh-base running on docker.  this is the error

Seneca Fatal Error
==================
Message: seneca: gate-executor: [TIMEOUT:z7en3mapswpc/dkj6xm1uexzi:11111<1465163235895-1465163224784:undefined]
Code: transport_listen
Details: { type: 'web',
  port: [Function],
  host: '0.0.0.0',
  path: '/act',
  protocol: 'http',
  timeout: 5555,
  max_listen_attempts: 11,
  attempt_delay: 222,
  serverOptions: {},
  pin: { role: 'karmasoc-web-server' },
.............
 at null._onTimeout (/src/node_modules/seneca/node_modules/gate-executor/gate-executor.js:112:21)

**this is my docker file**
# karmasoc-web-server
FROM node:4
RUN mkdir /src
ADD . /src/
WORKDIR /src
RUN npm install --unsafe-perm=true
EXPOSE 8200
EXPOSE 44000
EXPOSE 43000
CMD ["npm", "start"]

# build and run:
 $ docker build -t karmasoc-web-server .
 $ docker run -d  -h $(docker-machine ip default)  -p 8200:8200 -p 44000:44000 -p 43000:43000 -e HOST=$(docker-machine ip default)  -e JWT_SECRET=**** -e REDISCLOUD_URL=**** -e PATH_LOGFILE=** karmasoc-web-server

appreciate any help. let me know if you need any more details

**Comment by mirceaalexandru** [comment]
Hi @BhaskaranR ,

If you are using dockers then you should start them with ```--net=host```.

Also you should specify ```host="own-ip"``` on both mesh base and service.

Take a look on my PR for updating the Readme for details and let me know if it is working (see "Example Three" and "Deploying with Docker").

https://github.com/mirceaalexandru/seneca-mesh/blob/patch-1/README.md

**Comment by rjrodger** [comment]
version 1.0.0 (about to release!) will work with docker overlay networks (i.e docker swarm).
If not using an overlay then you have to use `--net=host` as per @mirceaalexandru

**Comment by alank64** [comment]
@mirceaalexandru can you also add...

If using docker-compose then add to your yml file in each service `network_mode: "host"`

Would be appreciated and thanks!

**Comment by rodmaz** [comment]
@rjrodger Any update on version 1.0.0? One year later we are in version 0.11.0. Does the current version work with Docker overlay networks? We have tried here and it seems like even though both containers (base and service) are in the same network, `gate-executor` generates a DEATH_LOOP.

```
/opt/project/node_modules/seneca/lib/common.js:276
        throw new Error('[DEATH LOOP]')
        ^

Error: [DEATH LOOP]
    at Seneca.die (/opt/project/node_modules/seneca/lib/common.js:276:15)
    at Object.intern.handle_reply (/opt/project/node_modules/seneca/seneca.js:1343:23)
    at Object.act_tm [as ontm] (/opt/project/node_modules/seneca/seneca.js:917:16)
    at Timeout.timeout_check [as _onTimeout] (/opt/project/node_modules/gate-executor/gate-executor.js:216:16)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
Waiting for the debugger to disconnect...
Debugger listening on ws://0.0.0.0:55376/20e1f9d6-356f-4567-913b-fe890f70c2a3
```

Service does found the base as we can see from the logs. However mesh base apparently tries to communicate back with the service in entries like these:

```
result: {
      "id": "attempt_delay:222,callmax:111111,hook:listen,host:0.0.0.0,ismesh:true,max_listen_attempts:11,model:consume,msgidlen:12,msgprefix:seneca_,path:/act,pin:cmd:recordEventApplicationDidOpen,role:analytics,port:57082,protocol:http,role:transport,serverOptions:[object Object],timeout:5555,type:web~vb6ugau4y16r/1504964905000/6/3.4.2/local~cmd:recordEventApplicationDidOpen,role:analytics~1504964907935"
    }
    plugin_name: "mesh"
    pattern: "hook:client,role:transport,type:web"
```

After a while, the service is disconnected with `DEATH_LOOP` error above.

**Comment by danielo515** [comment]
On my case it works, more or less, but I have lot of timeout errors resulting on dead_loops situations, not good.
