### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by raymondcarl** [rjrodger/seneca-mesh#37]
I've been learning about Node, Seneca, and Microservices.  Couldn't figure out how to create dynamic references to the network location of services, found Rodger's blog, and ended up here!

For some reason, I don't have the ability to tag this as a question, but a key question I have is about security with SWARM and Mesh.  This may be an idiotic questions, but I'm guessing this approach assumes that all the services operate in a private network (with maybe 1 public gateway)?  I have a very vague understanding of the protocol, but my next area I find confusing is how to keep services you don't create from being added into the picture.  Please feel free to let me know if there's a better venue to ask this question!

**Comment by rjrodger** [comment]
The SWIM network should be regarded as fully trusted internally with strict external boundaries.

You can achieve this in production using, say docker swarm, or an overlay network, or AWS VPC.
