### ISSUE TITLE
Question: Correct way to defer acts until available

### ISSUE THREAD

**Issue by mcdonnelldean** [rjrodger/seneca-mesh#4]
@rjrodger 

When I spin up a service I use mesh to add a user via seneca-user's register method. Right now I need to add a timeout of around 3 seconds to ensure this happens. The problem seems to be the variable amount of time it takes for services to mesh together (I don't think it actually takes 3 seconds, it's just a safe bet). I assume we can never reliably depend on timeouts since network and mesh size are variable.

Is there a hook in mesh that I could take advantage off to emit when a pin is available or gets meshed? I don't mind adding this in myself.

Or as an alternative, what recipes do you recommend that don't depend on timeouts?

**Comment by rjrodger** [comment]
on master, seneca.ready should do the trick, as it waits for meshing to finish

**Comment by mcdonnelldean** [comment]
Epic, I'll move to this and try it out.

**Comment by jacktuck** [comment]
Hey, @rjrodger. Out of curiosity, how do you determine when meshing has finished?
