### ISSUE TITLE
Question: meshing multiple pins

### ISSUE THREAD

**Issue by mcdonnelldean** [rjrodger/seneca-mesh#5]
@rjrodger I'm trying to play with more complex meshing. I have a number of services that now do point to point, plus listen, plus publish. I'd trying to figure out which way I define these so that they correctly publish or run point to point. I know how to make all or none, one or the other, but not how to define pins in the granular context below.

### Service A
`role:foo, info:bar` <-- I want to publish this to anyone who cares
`role:foo` <-- Except the pin above I want to handle these point to point
`role:zig` <-- I want to listen and respond point to point

### Service B
`role:foo, info:bar` <-- I'm on of the services that cares about this message
`role:zig, cmd: *` <-- I'm going to send a bunch of these to service A point to point
`role:zen` <-- I want to handle any messages that match point to point
`roles:zen, info:*` <-- I want to publish these to anyone who cares

**Comment by rjrodger** [comment]
```
require('seneca')({tag:'serviceA'})
  .use('mesh', {pin:'role:foo,info:bar'})
  .listen( { port:8001, pins:['role:foo','role:zig'] } )
```

```
require('seneca')({tag:'serviceB'})
  .use('mesh')
  .client( { pins:['role:foo','role:zig'], port: 8001 } )
  .listen{ port:8002, pins:['role:zen'] } )
```

**Comment by mcdonnelldean** [comment]
@rjrodger You know, I think my real question here is can I have multiple load balancer tasks per service each handling its own set of pins, or some sort of overlay

```
require('seneca')()
  .use('mesh', {
    auto: true,
    overlay: [
      {pins: ['role:foo', 'role:bar']}, // Will work point to point
      {pins: ['role:foo, info:zen', 'role:bar, info:zen'], model: 'publish'}, // Will publish
    ]
  })
```

I know it's not there now but would this make sense as a feature? It seems it would make meshing trivial.

**Comment by rjrodger** [comment]
Try s/overlay/listen/ :)

https://github.com/rjrodger/seneca-mesh/blob/master/mesh.js#L55

**Comment by mcdonnelldean** [comment]
Interesting! Can I drop the port? So my code above as,

```js
require('seneca')()
  .use('mesh')
  .listen({pin: 'role:foo', 'role:bar'})
  .listen({pins: ['role:foo, info:zen', 'role:bar, info:zen'], model: 'publish'})
```

**Comment by mcdonnelldean** [comment]
Ah! So I just read the code and your comment; you meant change it to listen!

```js
require('seneca')()
  .use('mesh', {
    auto: true,
    listen: [
      {pins: ['role:foo', 'role:bar']}, // Will work point to point
      {pins: ['role:foo, info:zen', 'role:bar, info:zen'], model: 'publish'}, // Will publish
    ]
  })
```

This is pretty epic! I'll add in a guide to the website for this :D

**Comment by andriy-zhelvachenko** [comment]
guys, does this work with published packages (to npm repo?). Or just with git codebase?

**Comment by mcdonnelldean** [comment]
@andriy-zhelvachenko Git for now, just put the git url in your package.json and reinstall.

**Comment by andriy-zhelvachenko** [comment]
In fact changes (v0.4.0) are already published to npmjs.org

Tnx

**Comment by andriy-zhelvachenko** [comment]
Guys, found very strange bug when using/testing these multiple pins

Basically if length & number of pattern properties exceed certain number then matching does not work

I will submit bug as separate jira

**Comment by andriy-zhelvachenko** [comment]
Here is the bug i meant
https://github.com/rjrodger/seneca-mesh/issues/8
