### ISSUE TITLE
Is it possible to separate mesh networks, i.e. dev instances from qa, and from prod?

### ISSUE THREAD

**Issue by andriy-zhelvachenko** [rjrodger/seneca-mesh#6]
@rjrodger, is there any configuration option that allows mesh services/clients to detect their network?

**Comment by rjrodger** [comment]
yes, on master, use options `tag` to create separate networks
works because: https://github.com/rjrodger/sneeze/blob/master/test/sneeze.test.js#L140
will publish seneca-mesh update soon

**Comment by andriy-zhelvachenko** [comment]
Tnx

**Comment by blanchma** [comment]
Sorry, can you explain it more clearly?
