### ISSUE TITLE
Pattern to find current port.

### ISSUE THREAD

**Issue by thekemkid** [rjrodger/seneca-mesh#7]
We have discovered the need arises to find the port which a service is currently listening on. @mcdonnelldean has suggested the following pattern: `role:mesh info:port`

**Comment by mcdonnelldean** [comment]
@rjrodger Context

In nodezoo our later tutorials break, when we introduce mesh we can no longer know which port we start on. I've checked `seneca.options()` to see if it gets dumped in there but it doesn't.

Given my assumption that this is variable in setup time I thought it would make sense for mesh to emit the value when it is know for people who want to log it to the terminal or logs.

**Comment by rjrodger** [comment]
you can override `role:transport,cmd:listen`, (just remember to call the prior) and capture the port that way
it should also appear in the logs

**Comment by mcdonnelldean** [comment]
I think I'll go with prior in nodezoo as a way to show it off a bit more.

**Comment by mcdonnelldean** [comment]
@thekemkid I'd say you can go ahead and close.
